async function boot () {

}

boot().catch(err => {
  console.error(err)
  process.exit(1)
})